Repository CMPUT301W21T05/KrowdTrialz, pull requests merged in 2021-03, with the labels that each got.

#93 Ignore Trials Functionality
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/T05/krowdtrialz/model/experiment/Experiment.java
  app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsNonOwnerActivity.java
  app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsOwnerActivity.java
  app/src/main/java/com/T05/krowdtrialz/ui/contributors/ContributorList.java
  app/src/main/java/com/T05/krowdtrialz/ui/contributors/ContributorsActivity.java
  app/src/main/java/com/T05/krowdtrialz/ui/owner/ContributorsActivity.java
  app/src/main/java/com/T05/krowdtrialz/ui/subscribed/SubscribedFragment.java
  app/src/main/java/com/T05/krowdtrialz/ui/subscribed/SubscribedViewModel.java
  app/src/main/java/com/T05/krowdtrialz/util/Database.java
  app/src/main/res/layout/activity_contributors.xml
  app/src/main/res/layout/activity_experiment_details_non_owner.xml
  app/src/main/res/layout/activity_experiment_details_owner.xml
  app/src/test/java/com/T05/krowdtrialz/ExperimentOwnerTest.java
Labels: Do not merge, Feature

#87 Experiment status
  app/src/main/java/com/T05/krowdtrialz/model/experiment/Experiment.java
  app/src/main/java/com/T05/krowdtrialz/util/ExperimentList.java
Labels: Feature

#94 workable access to owner experiment detail from search activity
  app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsNonOwnerActivity.java
  app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsOwnerActivity.java
  app/src/main/java/com/T05/krowdtrialz/ui/search/SearchActivity.java
  app/src/main/res/layout/activity_experiment_details_non_owner.xml
  app/src/main/res/layout/activity_experiment_details_owner.xml
  app/src/main/res/layout/experiment_list_element.xml
Labels: Feature

#97 Fix database getExperimentsByID
  app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsNonOwnerActivity.java
  app/src/main/java/com/T05/krowdtrialz/ui/ExperimentDetailsOwnerActivity.java
  app/src/main/java/com/T05/krowdtrialz/util/Database.java
Labels: Fix

#101 Fix error where experimentsList contained a null ArrayList
  app/src/main/java/com/T05/krowdtrialz/ui/subscribed/SubscribedViewModel.java
Labels: Fix

#118 Get timeplot to show
  app/src/main/res/layout/fragment_experiment_plots.xml
Labels: Fix
